### ISSUE TITLE
Can't execute rmview.py

### ISSUE THREAD

**Issue by Kratacoa** [bordaigorl/rmview#10]
When I execute `python src/rmview.py` it reports
``` python
File "src/rmview.py", line 156
  rmConnect(**self.config.get('ssh'),
                                                       ^
SyntaxError: invalid syntax
```
Without any real overview of the code, I've tried setting manualy `rmview.json` (since it never asked me to, because it didn't execute), but it had no effect. I followed the `pyrcc5` step beforehand. 
The system is an openSUSE, I've installed the `paramiko` package.

**Comment by bordaigorl** [comment]
Hi! Can you please specify which branch you are using?
My guess would be that `python` is actually calling python 2 instead of python 3 in your system...
what does `python -V` return?

**Comment by Kratacoa** [comment]
Yep, that was it, thank you. My bad!
Since I'm at it, is there any way to change the resolution? When I resize the screen to be bigger the result looks quite grainy (compared to my tablet's resolution); [It looks like this](https://imgur.com/a/dbDG38Z), you can see clearly the final *Z* being somewhat off while it's smooth on my tablet.

**Comment by bordaigorl** [comment]
That could be antialiasing artifacts. Try right-click > Actual size. That would not zoom the image and you get pixel per pixel what the tablet displays. If you zoom in/out you will have some approximations which are unavoidable.

**Comment by Kratacoa** [comment]
> That could be antialiasing artifacts. Try right-click > Actual size. That would not zoom the image and you get pixel per pixel what the tablet displays. If you zoom in/out you will have some approximations which are unavoidable.

Even at the "actual size" it is noticeable sometimes, depending on how the particular figure is shapen. 
Nonetheless, thank you for the support, and have a good time :)
