### ISSUE TITLE
Support for landscape mode in 2.10.0.324

### ISSUE THREAD

**Issue by dreadful-brain** [bordaigorl/rmview#102]
First thanks for making rmview work in 2.10.0.324. While working great in portrait, there is still an issue in landscape mode.
If you present a landscape file, and rotating rmview e.g. clock wise, rmview switches back to portrait mode as soon as you write something on rM.

**Comment by bordaigorl** [comment]
Yes that's part of the orientation-autodetection mechanism.
This should only happen if you set `"orientation": "auto"`.
What happens is that at every new frame, the autodetection tries to locate the UI buttons to determine if it's in landscape or portrait and adjust rotation accordingly.
The `"orientation": "auto_on_load"` setting restricts the autodetection to only the first frame, `"orientation": "portrait"` and `"orientation": "landscape"` disable the autodetection mechanism.

Could consider adding a menu entry to enable/disable autodetection.

**Comment by thomasvs** [comment]
I was surprised by this behavior as well.  It seems like it would be better to "remember" if the user rotated the display clockwise until the next time they change it manually?

btw, autodetect seems to work reasonably well when the menu is opened, but not when it's closed, even though that little circle stays there and ought to be enough to guess orientation?

**Comment by bordaigorl** [comment]
This was fixed in 166d6fcd92186feae48c754c4a07f66794499fd3
Now manually rotating disables auto-rotation.
