### ISSUE TITLE
[Bug…?] Unable to use rmview on rm2

### ISSUE THREAD

**Issue by TheOrdinaryWow** [bordaigorl/rmview#106]
System Version: Windows 10
reMarkable Version: 2.10.1.332 (ddvk-hacked)

I don't know in which step did I do wrong. After I connect to my remarkable it showed blank.

Although I'm using a standalone version, Python 3 (as well as pip3) is properly installed. I also enabled ScreenShare as instructed.

In addition I also tried modifying connecting method in the configuration file, yet still doesn't work.

It would be good if someone could please offer some help. Thanks!

This is the [gif](https://nzbcorzs-imgoss.oss-cn-shenzhen.aliyuncs.com/imgs/IMG_5299.GIF) of how I connect and how it failed.

**Comment by bordaigorl** [comment]
Have you tried using the stock software, without the ddvk-hack?
I've seen reports of the hack breaking ShareScreen...
[Also: what do you mean by "standalone" version?]

**Comment by TheOrdinaryWow** [comment]
My English is not that good, please accept my apology.

I meant that I download one from release , which you claimed to be the "standalone software".

If it's dvvk's bad so, I might need to wait till next update. Meanwhile please keep this open, much appreciated.

Have a next day dev :))

**Comment by bordaigorl** [comment]
Ah so that's the problem! The release you downloaded is old and does not support 2.10. But the current (unreleased) version that you can install via the `pip` method is compatible with 2.10.
I'll see if I can release the latest version.

**Comment by TheOrdinaryWow** [comment]
Problem solved. I compiled one as instructed and it worked.
Thanks! :))
