### ISSUE TITLE
works on wifi but not with eth over usb

### ISSUE THREAD

**Issue by vodkatad** [bordaigorl/rmview#112]
I've got a Remarkable2 and everything is working fine whenever I work on the local wifi network, but I cannot connect to it via eth over usb (10.11.99.1, accessing it with this IP indeed worked in the past...). I've activated the sharing via usb...the connection via ssh is not working either via the usb cable.
What am I missing? Thanks!

**Comment by dreadful-brain** [comment]
I had a similar problem using ScreenShare over USB on Win10 with default firewall, as the 10.11.99.1 interface is treated as public network and neither reMarkable-Desktop-App, nor rmview are automatically enabled for public networks by Win10. I had to enable exceptions in the fire wall for both Apps to make it work. Maybe that could be helpful for you.

**Comment by vodkatad** [comment]
Thanks, forgot to mention that I am using linux. Will troubleshoot a bit more ASAP (lots of solutions online but it worked out of the box previously so I am not sure I am needed to add new routes to my routing table...) and leave notes here.

**Comment by vodkatad** [comment]
OK, basically it is something related to the missed auto assigment of the ip/route to the USB device from the linux side.
I am closing this and putting the solution for the posterity (found it on reddit: https://www.reddit.com/r/RemarkableTablet/comments/ju361h/cannot_connect_to_rm2_over_usb_in_browser/)

```
root@rotpunkt:~# dmesg
...
[19473.677645] cdc_ether 1-4:1.0 usb0: register 'cdc_ether' at usb-0000:00:14.0-4, CDC Ethernet Device, 9a:cd:08:6a:54:d5
[19473.692686] cdc_ether 1-4:1.0 enx9acd086a54d5: renamed from usb0
root@rotpunkt:~# ip link set enx9acd086a54d5 up
root@rotpunkt:~# ip addr add 10.11.99.2/24 dev enx9acd086a54d5
```
