### ISSUE TITLE
rmview does not proceed with authentification

### ISSUE THREAD

**Issue by LabChameleon** [bordaigorl/rmview#114]
I have installed rmview via pip on ubuntu and I am using the remarkable patch 2.10. I have established a ssh key with the tablet
and I am able to connect to my tablet via ssh connection. However when using rmview its does not proceed with the authentification.
I get the following log and then nothing is happening anymore:
```

2021-11-24 09:21:51+0100 [-] Log opened.
[INFO] STARTING: Wed Nov 24 09:21:51 2021
[INFO] Searching configuration in rmview.json, /home/julian/.config/rmview.json
[INFO] Fetching configuration from /home/julian/.config/rmview.json
[INFO] Using known hosts file: /home/julian/.config/rmview_known_hosts
[INFO] Loaded known hosts from /home/julian/.config/rmview_known_hosts
[INFO] Connecting...
[INFO] Connected to 192.168.0.134
[INFO] Detected reMarkable 1.0
[INFO] Using backend 'screenshare'
[INFO] Connecting to ScreenShare, make sure you enable it
[WARNING] Authenticating, please wait...
2021-11-24 09:21:53+0100 [-] ChallengeReaderProtocol starting on 5901
2021-11-24 09:21:53+0100 [-] Starting protocol <rmview.screenstream.screenshare.ChallengeReaderProtocol object at 0x7f5ac04d8d60>
```

my config file is the following:

```
  1 {                                                                                                                                                                
  2     "ssh": { 
  3         "address": [ 
  4             "192.168.0.134" 
  5         ], 
  6         "auth_method": "key", 
  7         "key": "~/.ssh/remarkable" 
  8     }, 
  9     "orientation": "auto", 
 10     "pen_size": 15, 
 11     "pen_color": "red", 
 12     "pen_trail": 200 
 13 }
```

I have the screenshare feature activated on my tablet. Any insights what might be the problem?

**Comment by bordaigorl** [comment]
It looks like the ssh connection works, but the authentication with the tablet hangs.
It could be that the ports involved in the auth are not open?
Have a look here #111 to see if that helps.

**Comment by LabChameleon** [comment]
yes, apparently the problem seems to be similar. If I allow all incoming connections in my firewall the authentification works fine. I will however look for a better solution than just allowing all incoming connections.
That already helps a lot, thank you!
