### ISSUE TITLE
Support colour on software version 2.11

### ISSUE THREAD

**Issue by pks40** [bordaigorl/rmview#117]
Starting with software 2.11, for some pens there is now the possibility to select colours in addition to just black/grey/white (red/blue for the pens, and yellow/green/pink for the highlighter). These get exported in PDFs, and are (so they say) also available via ScreenShare.

It would be amazing to support them in rmview. Actually, I tried to just manually set `IMG_FORMAT = QImage.Format_RGB16` in `rmview/screenstream/common.py`, and this worked. So probably if software version >= 2.11 is detected, the colour image format should be used.

**Comment by bordaigorl** [comment]
Just got the update so I could test it myself.
Actually RGB16 worked on the old versions too it was just useless since the remarkable already grayscaled the output before it could be captured.
I'll push a patch soon.
