### ISSUE TITLE
Install Remarkable VNC files if not present

### ISSUE THREAD

**Issue by ChrisPattison** [bordaigorl/rmview#12]
Paramiko supports file transfers so rmview could check if `mxc_epdc_fb_damage.ko` and `rM-vnc-server` are present beforehand and transfer them if they are not. They could be included in the python package and even transferred to a temp directory every time. This would make setup as simple as pip installing rmview. 

I like the latter option of transferring the files every time to a temp directory out of the python package installation directory since it wouldn't require any setup on the side of the remarkable and doesn't leave any permanent changes

**Comment by ChrisPattison** [comment]
It's worth mentioning that both of these files sum to 350KiB which is quite small

**Comment by bordaigorl** [comment]
Yes I considered this but I thought it is not nice to upload binaries to the tablet and execute them without the user's explicit consent.
What I would consider is to include a button in the UI to explicitly request the transfer.

**Comment by ChrisPattison** [comment]
I'm a bit partial to a terminal interface but otherwise I generally agree about uploading/running binaries

**Comment by ChrisPattison** [comment]
I have in mind to start on a PR for this (like `rmview_install` ) at some point, but there is a dependency on PR #11

**Comment by ChrisPattison** [comment]
As a heads up, I am working on this (WIP!) at https://github.com/ChrisPattison/rmview/tree/install
I think there's some work to be done if we want something explicit like a UI button. My plan is to wire this into a config option 'auto_install' that defaults to false.

Separately, currently, there is no checksum or check of /proc/cpuid when the kernel module is loaded. It seems like we might want to

**Comment by bordaigorl** [comment]
Nice! Thanks.
Ideally one would start the program and be presented with a messagebox if the binaries are missing, with a button offering to install them automatically.
I can quickly add the UI if the logic is in place.
[I guess the best solution would be to have a proper settings dialog...]

**Comment by ChrisPattison** [comment]
> Nice! Thanks.
> Ideally one would start the program and be presented with a messagebox if the binaries are missing, with a button offering to install them automatically.
> I can quickly add the UI if the logic is in place.
> [I guess the best solution would be to have a proper settings dialog...]

This sounds great. The logic is there although it might be a bit troublesome to plumb in

**Comment by bordaigorl** [comment]
@ChrisPattison I added a branch with an alternative solution.
I included the binaries with the program resources so that installing does not need internet and we control the version and availability of the binaries.
Could you test it?

**Comment by ChrisPattison** [comment]
I've tested it on my end and it's all good. I think it's a great solution. One thing I would suggest is that the binaries go in a git submodule so that the repository isn't tracking diffs of binaries

**Comment by bordaigorl** [comment]
Thanks for testing and for the feedback!
As soon as I have the time to document this a bit I'll merge it.
I think for the moment submodules would be an overkill, I'm not expecting these binaries to be updated often if at all...but thanks for the idea, I'll keep it in mind if things change (for example if RM2 support happens).
