### ISSUE TITLE
Colors support

### ISSUE THREAD

**Issue by zelomel** [bordaigorl/rmview#120]
Hi @bordaigorl ,

is it possible to add the support of the new colors of the 2.11 version ?
If I don't make mistake, when I used vncviewer, my colored pdf was shown with colors.

Thanks for your work.

Z.

**Comment by bordaigorl** [comment]
This was recently added with 25c1867ece551f3f4f907505ff6ff89f0263a7f7 (also see #117).
AFAIK It only works if your tablet is updated to version 2.11.

**Comment by zelomel** [comment]
oh, I didn't even check if there was an upgrade. Sorry.
It works perfectly.
Z.
