### ISSUE TITLE
use without my.remarkable account

### ISSUE THREAD

**Issue by nift-d** [bordaigorl/rmview#121]
I keep getting time outs. is it because I don't have an my.remarkable account? reamdme says: 
> To use rmview with the ScreenShare feature you have to first start the ScreenShare from the tablet, and then start rmview

since I am using rm1 v2.9, but without an account I can not start ScreenShare before starting rmview. is the time out due to not having started ScreenShare? do I get around getting an account?

**Comment by bordaigorl** [comment]
I think this has been answered here #103 ?

**Comment by nift-d** [comment]
sorry, I looked for open issues only. so I guess I am gonna get an account then. this must be the "distraction free" experience they keep talking about..
