### ISSUE TITLE
Invalid private key

### ISSUE THREAD

**Issue by vdrummer** [bordaigorl/rmview#13]
Today I tried to use rmview and was unable to connect due to an invalid private key. The error persisted also after pulling the newest version.

The key I'm specifying in the config works fine when connecting to the rM via the `ssh` command.

Output of rmview is below:

```
Fetching configuration from remarkable/software/rmview/rmview.json
{'ssh': {'address': 'remarkable', 'username': 'root', 'key': '~/.ssh/id_rsa', 'timeout': 1}, 'orientation': 'landscape', 'pen_size': 15, 'pen_color': 'black', 'pen_trail': 0, 'background_color': 'black', 'fetch_frame_delay': 0.03, 'lz4_path_on_remarkable': '/usr/opt/lz4', 'hide_pen_on_press': False}
('Invalid private key', [_OpenSSLErrorWithText(code=67764350, lib=4, func=160, reason=126, reason_text=b'error:040A007E:rsa routines:RSA_check_key_ex:iqmp not inverse of
q')])
```

**Comment by bordaigorl** [comment]
Could it be an instance of this issue?
https://github.com/paramiko/paramiko/issues/340#issuecomment-492448662

**Comment by vdrummer** [comment]
Yep, it was indeed the format of the key that was causing problems, so the issue was on openSSH's side. I generated a new key with `-m PEM` and copied that over to the rM. Now everything works as expected again.

Thanks for pointing me to the issue!
