### ISSUE TITLE
VNcClient auth failed, currently ignored

### ISSUE THREAD

**Issue by vivek2000anand** [bordaigorl/rmview#157]
Hi,

I think remarkable updated to 3.7 today. I have a remarkable 2 which is updated to the latest version. Until it was updated to Version 3.7, rmview worked perfectly fine. However, after the update, it does not appear to work. The rmview window opens but it fails to connect to the remarkable. The issue appears to be with the VnClient versions but it could be something else. Here is the screen I get when I run `rmview -v config.json`. 

![rmview_error](https://github.com/bordaigorl/rmview/assets/37226693/4a76c554-9e69-4f1b-9b5b-110586fed767)

I am on Ubuntu 22.04.
How do you suggest I handle this?

**Comment by martinmeinke** [comment]
same issue on my end - have you found any solution?

**Comment by martinmeinke** [comment]
Solved it by overwriting `/etc/version` as outlined [here](https://github.com/bordaigorl/rmview/issues/146#issuecomment-1692646501)
