### ISSUE TITLE
Change the background canvas color

### ISSUE THREAD

**Issue by garethmarlow** [bordaigorl/rmview#16]
Absolutely superb job with this tool - thank you. I'm trying to use it with OBS and Chroma Key to superimpose Remarkable drawings real-time onto a video stream (Zoom call in this case). I can't get the Chroma Key working with a white background - can the background canvas color on rmview be changed? I was hoping that the bg_color option would do this but it doesn't seem to.

**Comment by garethmarlow** [comment]
I changed from Chroma to Color Key and it's now working - great use case. Nevertheless, question stands - is it possible to change the background canvas color?

**Comment by bordaigorl** [comment]
Hi! Glad you like the tool!
To do what you ask is equivalent to setting Color key: one would need to process the image replacing any white pixel with a pixel with a color of choice. That's exactly what Color key does for you so doing it in rmview would be redundant!
