### ISSUE TITLE
Program stopped working from one day to the next

### ISSUE THREAD

**Issue by lylethorngage** [bordaigorl/rmview#21]
I am sorry if this is not the right place to discuss this, still pretty new to all of it.
I have installed rmview successfully and it was working perfectly. However not anymore.
The steps I take to set up the server and connect with remarkable are the same, but for some reason the device refuses the connection.
I have tried replacing the rM-vnc-server script and its dependent, but I am stuck with the same result.

Any help?
Thank you

**Comment by bordaigorl** [comment]
I need more info to help:

- I assume we are talking about RM1?
- Do you get any error message if you run rmview from the console?
- Which OS are you on?
- Are you connecting via USB or WiFi?
- Which authentication method are you using?
- Can you successfully ssh in your RM with the same connection type?

[edit: sorry I closed the issue by mistake, now reopened]

**Comment by lylethorngage** [comment]
Hi, Thank you!

- RM1 yes, btw I would be very happy to know if and when support for 2 will be available. This thing you did is a game changer, cannot thank you enough.

- I run rm view from console, it starts the window, asks for address and password and THEN fails with connection rejection message

- I am on Mac OS 10.14.6 

- Connecting via USB

- Using SSH, which works fine from console. In fact I think that I am able to successfully launch rM-vnc-server, it all fails when I run rmview.

**Comment by aweiler** [comment]
Hi,

I can't get it to work on RM2 at the moment either. It used to work with my RM1. 

- I assume we are talking about RM1?
-> RM2, but will try with RM1 during the next days.

- Do you get any error message if you run rmview from the console?

```Searching configuration in rmview.json
Fetching configuration from rmview.json
{'ssh': {'address': '10.11.99.1', 'password': 'xxx', 'username': 'root', 'key': '~/.ssh/id_rsa', 'timeout': 2}, 'orientation': 'auto', 'pen_size': 10, 'pen_color': 'red', 'pen_trail': 1000, 'background_color': 'black', 'hide_pen_on_press': False}
Connecting...
Connected to 10.11.99.1
23/10/2020 12:40:23 Listening for VNC connections on TCP port 5900

Connection lost: Connection to the other side was lost in a non-clean fashion.
Stopping framebuffer thread...
Framebuffer thread stopped
```
and as a pop-up window
```Please check your reMarkable is properly configured, see the documentation for instructions.

Connection failed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 61: Connection refused.
]
```

- Which OS are you on?
MacOSX 10.15.7 (19H2)

- you connecting via USB or WiFi?
USB
- Which authentication method are you using?
ssh
- Can you successfully ssh in your RM with the same connection type?
yes. I can start the vnc server from the console without problems
```reMarkable: ~/ ./rM-vnc-server
23/10/2020 12:46:18 Listening for VNC connections on TCP port 5900
23/10/2020 12:46:18 Listening for VNC connections on TCP6 port 5900
```

**Comment by bordaigorl** [comment]
Thanks for the info.

**Support for RM2**
support for RM2 will not be something I can work on: I don't own a RM2.
The problem is that the way the framebuffer is handled has changed in RM2 and so the current way of fetching the screen updates on the table does not work.
You can still use the `ssh` branch which is not relying on the update mechanism. It's slower, but still very much usable.

**Connection problem**
I'm not sure what could be happening here.
Are you using the latest version from this repo?
One thing you could try is to start the vnc server from ssh and then start rmview and see if the server prints any error...

**Comment by lylethorngage** [comment]
Yes, the version is the latest. I have installed everything last week and it was working great. 
Perhaps you can tell me this: is there a specific place the files rM-vnc-server and mxc- etc should be located?
It is still strange because I did not change them since then, but maybe I can start everything from scratch and relocate them.

**Comment by bordaigorl** [comment]
>  Perhaps you can tell me this: is there a specific place the files rM-vnc-server and mxc- etc should be located?

They are assumed to live in `$HOME`.
(I had plans to make the paths customizable but I don't have much time to work on this atm)

**Comment by lylethorngage** [comment]
Alright, I solved the problem.
I simply removed all the files and started from scratch. Now it works, although I still do not understand what the problem might have been.

Thanks

**Comment by bordaigorl** [comment]
Something that is easy to forget is to set the files as executable on the tablet.
But I don't know how they could have lost that permission in your case, since it all seemed to work at some point.
Anyway, glad it has been resolved.
