### ISSUE TITLE
key parameter

### ISSUE THREAD

**Issue by RDeRenzi** [bordaigorl/rmview#24]
Hi Emanuele, 
thank you indeed for this fantastic tool. 
I just mention that I cannot get the following example.json parameter to work
"key": "~/.ssh/id_rsa"
The conf.json file works fine when I use the parameter
"password": "xxxxxx",
The message is '... not a valid RSA private key'. But the key  is valid: ssh root@ip_address works with no password.
Roberto

**Comment by bordaigorl** [comment]
My guess is that this is is a duplicate of #13 . Can you see if that solution works?
I will add a note to the readme.

**Comment by RDeRenzi** [comment]
Yes it is. Thanks!
