### ISSUE TITLE
Installation instruction missing

### ISSUE THREAD

**Issue by Dmarc** [bordaigorl/rmview#26]
Hi,

I'm probably stupid, but I can't find the instructions for installation of the vnc branch. In the readme, it just says to use 'pip install .'...I've unsuccessfully tried 'pip install rmview'. Could you specify the correct name of the package ?

Thanks,

Marc.

**Comment by bordaigorl** [comment]
You are not stupid! Build/packaging systems are all different and with their own quirks so it's normal to be puzzled :)

The installation instructions are correct but it's easy to miss the fact that the dot is important at the end of the line.
The command

    pip install .

(note the dot at the end)
will tell `pip` to install the package located at the current directory (`.`).
This will only work if you run it from the root directory of the repo of course.
Hope this helps!

**Comment by Dmarc** [comment]
You learn something new everyday !
I've never used pip this way before... Thanks for the very quick answer, and for this great piece of work !
