### ISSUE TITLE
Connection refused on RM2

### ISSUE THREAD

**Issue by Th0rgal** [bordaigorl/rmview#27]
Hello,

I am running nixos 20.09 and I installed the rmview dependencies through conda, then I built the rmview.whl and installed it with pip. I tried to connect with the example config but here is what I got:
![2020-12-08-181430_520x203_escrotum](https://user-images.githubusercontent.com/41830259/101517665-4a986d80-3981-11eb-9b82-42e6eb432746.png)

Unfortunately when I typed, nothing appeared on the screen. Since I wasn't able to write my passphrase, I edited the config to provide my password, this time it didn't ask me anything but I got this error:
![2020-12-08-181642_1920x1080_escrotum](https://user-images.githubusercontent.com/41830259/101517924-94815380-3981-11eb-8f98-03099f5a7435.png)

Thank you for your help,
Thomas

**Comment by bordaigorl** [comment]
First: the example configuration is not meant to be used directly but needs to be adapted with your configuration parameters. So in your case you probably want to remove the `key` setting. The address in the example config is the default one when connecting via USB. Make sure you can connect via ssh on USB with the tablet.

Second: have you installed the dependencies on the tablet?

**Comment by Th0rgal** [comment]
> First: the example configuration is not meant to be used directly but needs to be adapted with your configuration parameters. So in your case you probably want to remove the `key` setting. The address in the example config is the default one when connecting via USB. Make sure you can connect via ssh on USB with the tablet.
> 
> Second: have you installed the dependencies on the tablet?

The default configuration was fine to me (my ssh key is in the default location):
```
{
  "ssh": {
    "address": "10.11.99.1",
    "username": "root",
    "key": "~/.ssh/id_rsa",
    "timeout": 2
  },
  "orientation": "auto",
  "pen_size": 10,
  "pen_color": "red",
  "pen_trail": 1000,
  "background_color": "black",
  "hide_pen_on_press": false
}
```

The modified version with my password had the other bug.

Second: yep I installed them with these commands:
```sh
scp rM-vnc-server root@remarkable:rM-vnc-server
scp mxc_epdc_fb_damage.ko root@remarkable:mxc_epdc_fb_damage.ko
ssh root@remarkable chmod +x rM-vnc-server
```

**Comment by bordaigorl** [comment]
Ok thanks for the info.
What happens if you run

    ssh 10.11.99.1 '/sbin/insmod $HOME/mxc_epdc_fb_damage.ko; $HOME/rM-vnc-server'

If everything is in order, you should see something like `Listening for VNC connections on TCP port 5900` and you can exit by pressing `ctrl+C`.

**Comment by Th0rgal** [comment]
> Ok thanks for the info.
> What happens if you run
> 
> ```
> ssh 10.11.99.1 '/sbin/insmod $HOME/mxc_epdc_fb_damage.ko; $HOME/rM-vnc-server'
> ```
> 
> If everything is in order, you should see something like `Listening for VNC connections on TCP port 5900` and you can exit by pressing `ctrl+C`.

So here is what I tried:
```
╰─ ssh root@10.11.99.1 '/sbin/insmod $HOME/mxc_epdc_fb_damage.ko; $HOME/rM-vnc-server'
Enter passphrase for key '/home/thomas/.ssh/id_rsa':
insmod: ERROR: could not insert module /home/root/mxc_epdc_fb_damage.ko: Invalid module format
09/12/2020 11:10:27 Listening for VNC connections on TCP port 5900
09/12/2020 11:10:27 Listening for VNC connections on TCP6 port 5900
```

**Comment by bordaigorl** [comment]
Ok so the error message suggests the kernel is different from the one `mxc_epdc_fb_damage.ko` was compiled against.
Is this RM1 or RM2?

**Comment by Th0rgal** [comment]
It is RM2, is there a different version for RM2?

**Comment by bordaigorl** [comment]
Ah well, as the Readme says, only rm1 is supported. I'll amend the readme to state that more prominently.
Currently there's no version for RM2, see #22 .
You may try with an experimental version of reStream.
I don't own an RM2 so I cannot test things.
There are very capable devs looking into ways of getting something like rmview working for RM2 when those methods are mature enough I'll do my best to integrate them in rmview.
But for now, it's just not supported I'm afraid....

**Comment by bordaigorl** [comment]
I'll close as duplicate, let's collect all info on this topic on #22
