### ISSUE TITLE
Python window does not open

### ISSUE THREAD

**Issue by JKosugi** [bordaigorl/rmview#30]
Hello everyone,

thank you for developing review. Its been really helpful so far!

Recently however I had an issue with the python window. From one day to the other it wasn't opening anymore. The computer seems to connect the Remarkable. 

```
(base) Johanness-MacBook-Pro:rmview Johannes$ rmview
Searching configuration in rmview.json, /Users/Johannes/Documents/Remarkable/rmview-vnc/rmview.json
Fetching configuration from rmview.json
{'ssh': {'address': '10.11.99.1', 'username': 'root', 'key': '~/.ssh/id_rsa', 'timeout': 2}, 'orientation': 'auto', 'pen_size': 10, 'pen_color': 'red', 'pen_trail': 1000, 'background_color': 'black', 'hide_pen_on_press': False}
Connecting...
Connected to 10.11.99.1
```

And the icon also does appear...
<img width="784" alt="Screenshot 2020-12-18 at 14 55 12" src="https://user-images.githubusercontent.com/76213490/102622340-2850dd80-4141-11eb-8a07-e233a5d8ef82.png">

I have the anaconda installation of python.

Thank you for your help in advance!

**Comment by bordaigorl** [comment]
That is odd...have you updated something since last time it worked?
I would try to see if the window was displayed off-screen or on secondary screens...

**Comment by JKosugi** [comment]
Thank you for your help. I solved the issue by removing all dependencies and reinstalling rmview which did the job. The issue might have been apples latest mac os update "Big Sur" update.
