### ISSUE TITLE
Syntax error in rmview.py?

### ISSUE THREAD

**Issue by cindy-jth** [bordaigorl/rmview#32]
rmview.py would not run, telling me that there is a syntax error on line 171

File "/Downloads/rmview-vnc/src/rmview/rmview.py", line 171
    rMConnect(**self.config.get('ssh'),
                                                              ^
SyntaxError: invalid syntax

**Comment by bordaigorl** [comment]
Syntax errors are a telltale sign that you might be using Python 2 instead of Python 3.
I would adivse you to manage your python versions with pyenv.
What does `python --version` return?

**Comment by cindy-jth** [comment]
Oh yes, that's a problem. How do you make python call python3? I do have it downloaded. (on Mac)

**Comment by bordaigorl** [comment]
That depends a lot on the OS you are using.
In general it is a good idea to use [pyenv](https://github.com/pyenv/pyenv) to manage multiple versions on the same system.
If you think you installed Python 3, you should be able to call `python3` and `pip3` from your console.

**Comment by cindy-jth** [comment]
Another issue came up, and I'm not sure what's going on:
  
File "/Downloads/rmview-vnc/src/rmview/rmview.py", line 5, in <module>
    from . import resources
ImportError: attempted relative import with no known parent package

**Comment by bordaigorl** [comment]
Are you following the instructions on the Readme or doing something different?
If you do `pip3 install .` from the root folder of the repo, you should then be able to just run `rmview` from the console.
If you want to manually run the script, you should use `python3 -m rmview`.

**Comment by cindy-jth** [comment]
I am following the instructions on the Readme, but for me pip3 install . would not work, so I had to install twisted and the other packages separately. I'm not sure where things went wrong.

**Comment by bordaigorl** [comment]
What is the error you get if you run `pip3 install .`? Which operating system are you using?
If you give me more info on the precise errors you are getting I can try and help.

**Comment by cindy-jth** [comment]
I'm on Mac OS the latest version and I have X code installed. When I run pip3 install . I get:

ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

Thanks for the help! I do not know if this is helpful or not, but the rmview-vnc folder is currently in my downloads folder.

**Comment by bordaigorl** [comment]
Ah I was suspecting that. You need to run `pip3 install .` from the top-level folder of rmview.
This most likely means running `cd ~/Downloads/rmview-vnc` on the console, but it really depends on where you downloaded rmview.

**Comment by cindy-jth** [comment]
It installed! What's the proper command line for running the application? Just to make sure I don't do it wrong.

**Comment by bordaigorl** [comment]
`rmview` should now work from anywhere, type it in the console and the app should launch.
It is possible to have a launcher but that's a bit more involved.

**Comment by cindy-jth** [comment]
I get this message when running it: "I could not connect to the reMarkable at 10.11.99.1:
No authentication methods available." Does that mean I have to connect to the remarkable via ssh first? (I do have my remarkable plugged in to my computer.)

**Comment by bordaigorl** [comment]
The simplest way is to provide your tablet password in the config file as documented in the Readme.
I am in the middle of making the config part more user-friendly so unfortunately you got a version that does not ask for the password by default.
The most convenient way would be to setup ssh so you can authenticate using a key.

**Comment by cindy-jth** [comment]
Where do I put the config file? I tried under the rmview-vnc folder where the example.json is located, but that didn't work, so I tried the src folder, but that also did not work. I named my file test.json and ran rmview [test]

**Comment by bordaigorl** [comment]
The `[config]` instructions use the common notation of enclosing in square brackets the parameters that are optional.
So the right way for you to invoke the script is `rmview test.json`. This assumes you are running `rmview` from the folder where `test.json` is. Otherwise you need to specify the full path, like `rmview ~/Downloads/rmview-vnc/test.json`.

**Comment by cindy-jth** [comment]
Thank you! Last question, when I set background_color to black, the window is still white. Is black not a recognized color?

**Comment by bordaigorl** [comment]
Ah no, there's a typo! It should be `bg_color` instead of `background_color`!
Thanks for reporting.
In any case that setting changes the background of the window, the area where the tablet's screen is reproduced will still have white background.
