### ISSUE TITLE
RM2 seems to be in pen tracking mode only

### ISSUE THREAD

**Issue by MechEng70** [bordaigorl/rmview#35]
First of all, great product.  It seems to be very responsive. However, when the pen is in contact with the screen, the rmview thinks that it is hovering and doesn't apply ink to the canvas.

**Comment by bordaigorl** [comment]
Could you please add some details on your environment:
- Operating System (on computer)
- version of reMarkable (1 or 2)
- do you use any hacks on the tablet
- method of installation or rMview
- rMview configuration settings (erase sensitive info before posting)

The pen tracking and the drawing are handled completely independently of each other.
The fact that you don't see "ink" appearing means the server is not sending the updates, or the client is not handling them properly. Do you see the screen at all?

**Comment by MechEng70** [comment]
OS - MacOS 10.15.7
RM2
INSTALLED Hacks
1. ReMarkable Hacks: https://github.com/ddvk/remarkable-hacks
sh -c "$(wget https://raw.githubusercontent.com/ddvk/remarkable-hacks/master/patch.sh -O-)" _ patch_17.2.04
2. Jagged line issue.  cd recept, git pull and run install. (8)

Installed with app file from downloads
Only change to configuration settings was from red to black.  red was doing the same thing as black.

On mac - only see where the pen on the RM2 is located and moved.  The movements on the RM2 are working and create lines.  On the mac, it briefly shows the line being drawn then disappears.

Video:
https://photos.app.goo.gl/3RfhtgF6q6iPbJH86

**Comment by bordaigorl** [comment]
Thanks the video is very helpful!
Ok, so from the video I see there's no data about the screen being transmitted/received.
The pen tracker hides on press by design. The image on the computer screen is completely blank but it should show the reMarkable toolbar. This means the screen updates are not being handled correctly.
Did you follow the auto-install method for installing the VNC server on the remarkable?
Could you try without the reMarkable hacks and with just the stock app?

**Comment by MechEng70** [comment]
I thought I followed the auto-install on the MAC.  I remember that it mentioned downloading and installing.  Did I miss a crucial step?
Just went and tried it again and it is only displaying the lock screen on the RMview while the RM2 is already unlocked.

The rm2fb has been updated to the following version: rm2fb - 1.0.0-3 from toltec.
**This seems to be the issue...** 

Not sure how to remove the hacks completely, I assume that I would have to downgrade the rm2 to the remarkable only FW???

**Comment by bordaigorl** [comment]
So: you have multiple hacks. One is remarkable-hacks, which should be compatible with rMview.
Then there is rm2fb which is *not compatible* with rMview for the moment (people are working on a solution).
So to make rMview you should disable rm2fb (or uninstall it), reboot the tablet and then try again with rMview.

**Comment by MechEng70** [comment]
Removed rm2fb and it works as expected.

**Comment by bordaigorl** [comment]
Great thanks for reporting.
I added a warning in the Readme for users of rm2fb.
Hopefully it will be made compatible in the near future.
