### ISSUE TITLE
Unable to Initalize Application and Issues with Settings Initialization

### ISSUE THREAD

**Issue by Legohead259** [bordaigorl/rmview#36]
I am on a Windows 64-bit laptop. I had to install the dependencies manually with Python 3.9, but also ran the automatic install command afterwards. When I try to run the program, I am unable to connect to the RM2 because it cannot find the SSH host key. Glancing at the source code, it appears to only be looking in UNIX directories - which is obviously an issue on a Windows laptop. When I tried to enable the "insecure_auto_add_host" option, the program crashes because the JSON settings file is not created. Thusfar, it is completely worthless on my PC and I would very much appreciate an explanation how the [author got it to work on a Windows machine](https://www.reddit.com/r/RemarkableTablet/comments/hc22nk/live_viewer_on_windows/fvgwlk2?utm_source=share&utm_medium=web2x&context=3).

**Comment by bordaigorl** [comment]
I am a bit confused by the description of your problem.
Have you tried to connect using user and password?
I don't understand what you mean by "the program crashes because the JSON settings file is not created"...
the idea is that you should create a text file with the JSON code with your settings, then call `rmview PATH_OF_YOUR_FILE` so that the tool finds the file. You can also just use the default location for the JSON file by running `rmview`, inserting the connection parameters when prompted and then if an error dialog displays you should see a "Settings" button. Click on it and the default configuration file should appear. Modify and save it, then relaunch rmview.

**Comment by Legohead259** [comment]
I have tried connecting with the username and password. Even with the correct information, I get a pop up saying that the it is unable to connect because the server host is unknown
![image](https://user-images.githubusercontent.com/8077426/103555631-ca750300-4e6d-11eb-8a12-1b633f56c5e3.png)



For the settings issue, I was initially getting this error:
```
Searching configuration in rmview.json, C:/Users/legoh/AppData/Local/python\rmview.json
QWindowsWindow::setGeometry: Unable to set geometry 100x200+640+275 (frame: 118x247+631+237) on QWidgetWindow/"QtImageViewerClassWindow" on "\\.\DISPLAY1". Resulting geometry: 148x200+640+275 (frame: 166x247+631+237) margins: 9, 38, 9, 9)
{'ssh': {'address': '10.11.99.1', 'password': '**********'}}
Connecting...
Could not connect to 10.11.99.1: Server '10.11.99.1' not found in known_hosts
Please check your remarkable is connected and retry.
Server '10.11.99.1' not found in known_hosts
Traceback (most recent call last):
  File "c:\users\legoh\appdata\local\programs\python\python39\lib\site-packages\rmview\rmview.py", line 400, in connectionError
    self.openSettings(prompt=False)
  File "c:\users\legoh\appdata\local\programs\python\python39\lib\site-packages\rmview\rmview.py", line 338, in openSettings
    with open(confpath, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\legoh\\AppData\\Local\\python\\rmview.json'
```

Now, I have created the "python" folder where it expects it and it still crashes when I click on the "settings" button.
```
Searching configuration in rmview.json, C:/Users/legoh/AppData/Local/python\rmview.json
Fetching configuration from C:/Users/legoh/AppData/Local/python\rmview.json
{'ssh': {'address': '10.11.99.1', 'password': '**********'}, 'orientation': 'auto', 'pen_size': 15, 'pen_color': 'red', 'pen_trail': 200}
Connecting...
Could not connect to 10.11.99.1: Server '10.11.99.1' not found in known_hosts
Please check your remarkable is connected and retry.
Server '10.11.99.1' not found in known_hosts

Bye!
```

**Comment by Legohead259** [comment]
I also just added `"insecure_auto_add_host": true` to the JSON file and still get the same errors.

**Comment by bordaigorl** [comment]
Thanks that's useful information.
There are two unrelated problems, one with the crash when pressing "Settings..." the other with the connection parameters.

For the settings button: you are right there is a bug, I'm going to push a fix soon.
If you make sure the file at the math in the first line of the log exists, what does the crash report when you press "Settings"?

For the connection parameters:
are you specifying `"insecure_auto_add_host": true` inside the `ssh` section?
Could you post the configuration file and the output?

A quick way out would be to connect to the tablet with `ssh` manually from a terminal and then follow the instructions for updating the known hosts...

**Comment by Legohead259** [comment]
Good. I'm sorry my initial explanation wasn't clear. 

Is there a separate log file for crash reports? What I posted is verbatim directly from the terminal; there doesn't seem to be a crash log printed there. Just closes and says, "Bye!"

I've got it to recognize the SSH key now. I was using the PuTTY terminal, not a command terminal which was putting the SSH key somewhere the program was not expecting. If I can make a recommendation, please include a guide on how to generate the SSH key in the README. 

Besides the "settings" button issue, the program works as expected now.

**Comment by bordaigorl** [comment]
I don't have a Window machine and SSH is not really native there (or maybe nowadays it is) so there might be many ways to handle the connection parameters system-wide. I might revise how host keys are handled by rMview in the future.
In the meantime, I'd be grateful if you added a page to the wiki (it should be freely editable) with the instruction you'd have wanted to see in the Readme, so I can point there if others have the same problem.

**Comment by Legohead259** [comment]
Ok. I also ran into some other issues that I was able to resolve myself. Would it be alright if I created an install guide for Windows on that Wiki page?

**Comment by bordaigorl** [comment]
That would be amazing thanks!
