### ISSUE TITLE
Package reMarkable rM-vnc-server-standalone dependency in toltec

### ISSUE THREAD

**Issue by Eeems** [bordaigorl/rmview#38]
Ideally this should be in toltec for easier distribution and updates.

**Comment by NickHu** [comment]
rM-vnc-server is written by @pl-semiotics so this should go here https://github.com/pl-semiotics/rM-vnc-server/issues/7

**Comment by NickHu** [comment]
Why are the binaries duplicated in this repo anyway? It's quite redundant as they come from here: https://github.com/pl-semiotics/rM-vnc-server/releases

**Comment by Eeems** [comment]
@NickHu I think you'll find that a lot of GitHub repositories have external dependency binaries added to their repo.

Thanks for pointing out that I opened this on the wrong repo though, I guess I wasn't looking closely enough at the readme and thought it was part of this project.

**Comment by NickHu** [comment]
Git repositories are not meant for storing binaries. The autoinstall that this package provides of rM-vnc-server can be replaced with `wget` and `chmod +x` which are already installed on the reMarkable; nonetheless, the best solution is probably to have it in a centralised package manager

**Comment by Eeems** [comment]
> 
> 
> Git repositories are not meant for storing binaries.

As I keep telling my coworkers.

> The autoinstall that this package provides of rM-vnc-server can be replaced with `wget` and `chmod +x` which are already installed on the reMarkable; nonetheless, the best solution is probably to have it in a centralised package manager

For sure, and it can also validate the binary with a sha256sum like toltec does.
