### ISSUE TITLE
Closing application/window with CTRL+Q/CRTL+W on Linux

### ISSUE THREAD

**Issue by epiasini** [bordaigorl/rmview#39]
Hi,

First of all, thanks a lot for rmview! It's been super useful to turn my remarkable into a little whiteboard I can use on Zoom calls. I have been using it succesfully on my RM1 and, more recently, RM2.

Anyway, here is a small issue I've been experiencing, in case you find the feedback useful.

I am on Ubuntu 18.04, and I use a tiling window manager (i3wm), which by default doesn't show window frames. This means that I don't have a "close" button to click to terminate the application when I'm done with rmview (II imagine that e.g. on gnome one is expected to close rmview by clicking on the usual 'x' in the upper right corner). Most applications will close the current window/tab (or terminate altogether) when receiving the CTRL+W (or CTRL+Q) keyboard shortcut (for instance, it is listed as a standard application shortcut in the GNOME guidelines: https://developer.gnome.org/hig/stable/keyboard-input.html.en), and that's how I usually close GUIs. This doesn't seem to work with rmview, so I am typically left to kill the application when I'm done with it. This is of course not a problem at all, but still I thought it'd be useful to flag it as something you may potentially look into at some point in the future. Unless I've overlooked something, in which case I apologise in advance!

**Comment by bordaigorl** [comment]
Hi thanks for the feedback.
This is a bit strange as Ctrl+Q should be bound to quitting the app by PyQt by default (it is on MacOs).
I added a Quit menu to the context menu for good measure 😉

**Comment by epiasini** [comment]
Awesome, thanks! I just gave it a try, and quitting from the context menu works great!

**Comment by Kami** [comment]
Just a heads up, I implement CTRL+C handler for the terminal window in #54.

That one handles CTRL+C inside the terminal where ``rmview`` is started and running, but I believe it should be straight forward to also handle CTRL+C inside the main QT window.
