### ISSUE TITLE
rmview stops updating its view  

### ISSUE THREAD

**Issue by kalmarek** [bordaigorl/rmview#44]
after document is set to landscape view.

Steps to reproduce:

1. open a notebook in portrait mode on rm2
2. start rmview and connect to rm2
3. set notebook to landscape view

**Comment by bordaigorl** [comment]
I don't own an RM2 so I cannot try and reproduce this.
I cannot see, however, any reason for why landscape view should trigger any change in the view updates at all.
Could you maybe produce a video of the problem?

Knowing which OS you are using and which method of installation for rmview you picked, would also help.
Just to make sure: can you confirm you are not using `rm2fb`?

**Comment by kalmarek** [comment]
this is stock firmware for rm2, rmview is my first modification ;) (btw: rmview is great! thanks so much for the effort of putting it together!)

I'm using Arch, with manual installation (pyrcc5, scp vnc-...-standalone, cd ./rmview/src/, `python -m rmview`)

**Comment by kalmarek** [comment]
interesting enough, today I can't reproduce that :D sorry to bother.

on the other hand, would it be possible to change the orientation dynamically (currently, when changing rm2 to landscape mode rmview displays correctly, but doesn't rotate the image)

**Comment by stheid** [comment]
@kalmarek BTW, there is actually an AUR for this project.

**Comment by bordaigorl** [comment]
> would it be possible to change the orientation dynamically

Not directly: there's no signal emitted by the tablet when you select landscape.
So only indirect methods remain.

One such is the one I use in the auto detection of orientation on startup `detectOrientation`: it probes few pixels to see where the UI widgets are and infers the orientation from that (very heuristic and there are some configurations ---like left-handed--- that make the UI ambiguous).
[This is activated with the `"orientation": "auto"` setting]
Calling the auto-detection on each update can be done (you could try to call it at `onNewFrame`) but seems wasteful.

**Comment by bordaigorl** [comment]
I retract the "wasteful" comment. You can test it by commenting line 309 in `rmview.py`.
I may include an option to enable this.

**Comment by kalmarek** [comment]
@bordaigorl maybe I'm missing something, but why not have a look at aspect ratio of the fetched image?

----
EDIT: hmmm, that's what rmViewApp is doing, right?
```python
    self.orient = None
    orient = self.config.get('orientation', 'landscape')
    if orient == 'landscape':
      self.viewer.rotateCW()
      self.autoResize(WIDTH / HEIGHT)
    elif orient == 'portrait':
      self.autoResize(HEIGHT / WIDTH)
    else: # orient
      self.autoResize(HEIGHT / WIDTH)
      self.orient = True
```

**Comment by bordaigorl** [comment]
The aspect ratio is always the same: when you select landscape on the tablet you simply tell the UI to move around the buttons and rotate the icons. If you read the data from the screen you still see it arranged in portrait, nothing changed (if it did there would be no need to handle it specially, we would already be receiving a rotated image).

The code you are quoting is doing something completely different: it's reading the `orientation` option and setting the aspect ratio of the window accordingly.
