### ISSUE TITLE
Rmview for IOS

### ISSUE THREAD

**Issue by BogdanS** [bordaigorl/rmview#50]
Would it be possible to create an IOS app with this functionality?
I'm sure it would be very popular.

**Comment by bordaigorl** [comment]
I think this would require a rewrite of rmview, as the current setup cannot be just ported to IOS as is.
What you can do is install a VNC client for IOS and manually start the VNC server on the tablet...

**Comment by stheid** [comment]
Further reading: https://github.com/pl-semiotics/rM-vnc-server#usage
rmview basically automatically deployes and starts this vnc server implementation on the remarkable and provides a vncclient implementation.
