### ISSUE TITLE
rmview stopped working

### ISSUE THREAD

**Issue by piforce** [bordaigorl/rmview#56]
after installing rmview it worked flawless on both of my windows devices. 
After installing toltec/remux the screen appears in rm view when write or push an action the screen flickers onetime and after that the remarkable doesn't respond anymore.

**Comment by bordaigorl** [comment]
You most probably are on RM2 and installed rm2fb.
The Readme states that rmview is currently not compatible with rm2fb.
The next release of the VNC server should fix this but it's still under development.

**Comment by piforce** [comment]
That wil be it then. Thanks for the quick reply. I missed it in the readme.
