### ISSUE TITLE
White screen on Windows

### ISSUE THREAD

**Issue by adem** [bordaigorl/rmview#6]
It seems that at least for me, only a white screen is displayed on Windows. I'm planning on taking a look at the issue (very little Python, no Qt experience) and preparing a patch in case I succeed, but I'd like to hear from others and their experience on Windows?

Thanks!

**Comment by wouterdhooghe** [comment]
Great project! This is the furthest I got on windows to an actual screencast of the remarkable input.

However I can confirm the white screen on windows 10. The red dot does show though and moves along with the remarkable stylus. Unfortunately no actual pen strokes are displayed in the application window. Also the standard orientation seems wrong: landscape with x and y inverted.

**Comment by bordaigorl** [comment]
I tested it on Win10 and it works out of the box for me.
Can you try to see which step is breaking?
Maybe inject some debug prints with

        self.fbworker.signals.onNewFrame.connect(lambda image: print("ok"))

after line 130.

**Comment by wouterdhooghe** [comment]
Hey thanks for your quick response. I added the debug print but it doesn't show any output in the console so i guess the program does not reach this line? I'm not very good with python so i couldn't detect which line fails. 
<img width="1280" alt="72WSvhbbj4" src="https://user-images.githubusercontent.com/3301671/80915187-ed846b80-8d50-11ea-92a7-27b62ca98a0d.png">

**Comment by bordaigorl** [comment]
Ok I will need help in debugging this since I cannot reproduce it.
Can you tell me which options you are using?
And which version of PyQt?
What do you see in the standard output?

**Comment by mrwth** [comment]
I have the same issue. On Windows 10, Anaconda distribution of Python 3.7 (all packages up to date), pyqt has version 5.9.2.  LZ4 is on the remarkable. No options (also no options file). Nothing in the output  (after "Connected to 10.11.99.1"). The newest version of rmview.

One additional thing which might be helpful - after the connection the displayed white window covered only a part of the remarkable screen - when I moved the pen, the red dot was not at the corresponding position. After I moved the pen to all the corners, this little problem disappeared.

**Comment by bordaigorl** [comment]
Can you try the "fit to window" action from the context menu or "Actual size" or resizing the window? Trying to understand if it's a display problem

**Comment by bordaigorl** [comment]
Also: can you try commenting out lines 73-77 (included) in workers.py and see if you get an error message?

**Comment by mrwth** [comment]
commenting out produces Error: <class '_lz4framed.Lz4FramedNoDataError'> in the terminal and a window with the message "Please check your reMarkable is properly configured with LZ4 installed".
(resizing the window doesn't change anything)

**Comment by bordaigorl** [comment]
Ok that helps. It would seem that LZ4 is working on the remarkable, but somehow no data is being transmitted.
Could you add

    print(rmerr.read().decode('ascii'), rmstream.channel.recv_exit_status())

before line 82 in `workers.py`.

**Comment by mrwth** [comment]
gives me
NameError: name 'rmerr' is not defined

**Comment by bordaigorl** [comment]
AH!!!! try running

    ssh 10.11.99.1 chmod +x lz4

**Comment by mrwth** [comment]
done; now I get

Error: <class 'AttributeError'> type object 'QImage' has no attribute 'Format_Grayscale16'

**Comment by bordaigorl** [comment]
Progress!
Version of PyQt?

**Comment by mrwth** [comment]
5.9.2

**Comment by bordaigorl** [comment]
Ah there's the problem! From the docs:

> `QImage.Format_Grayscale16` The image is stored using an 16-bit grayscale format. **(added in Qt 5.13)**

Now, one solution is upgrading Qt. The other is replacing
`QImage.Format_Grayscale16` with `QImage.Format_RGB16` in `workers.py`.

**Comment by mrwth** [comment]
I made the edit and it works now! Thanks!

**Comment by bordaigorl** [comment]
Fantastic. I'll push a fix. Thanks so much for helping me debug!
