### ISSUE TITLE
Incompatibility with new rM update?

### ISSUE THREAD

**Issue by lylethorngage** [bordaigorl/rmview#60]
Hi! Let me first say: thanks a lot for your work: rmview is an essential feature that makes using the remarkable a competitive option w.r.t. other tablets (and a much better one in my opinion).

Unfortunately, my remarkable 2 updated on its own today (my bad for not blocking auto updates), and it now seems impossible to restore a connection using rmview.
I have tried everything: from reinstalling rmview to removing all ssh keys associated to the old rM and adding new ones, to tweaking the settings... Nothing seems to work, and I keep getting 

> Connection failed: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 61: Connection refused.

I do manage to connect using manual ssh. 

Now this is critical because I am currently using rM and rmview for work, so any help will be greatly appreciated.

Thank you!

**Comment by d-falck** [comment]
Agreed that this is urgent for those of us who rely on this fantastic package! Same as issue #57, btw, and is really a problem with [rM-vnc-server](https://github.com/pl-semiotics/rM-vnc-server)
Duplicate of #57

**Comment by lylethorngage** [comment]
Oh Thanks, I didn't notice. Will keep an eye on that for resolutions.
