### ISSUE TITLE
Can't connect remarkable 1 using rmview ssh from Mac

### ISSUE THREAD

**Issue by alexcabezas1** [bordaigorl/rmview#68]
I can't connect to my remarkable 1. I tried vnc and ssh on a MacBook Pro.

**Comment by bordaigorl** [comment]
Sorry to hear that, but without any further clue on how to reproduce your problem, I cannot even try to help...
Have you followed the instructions of the [README](https://github.com/bordaigorl/rmview#readme)?
Which installation method did you use? What error message do you get?

**Comment by siraben** [comment]
@alexcabezas1 I am on a Mac and can connect to my reMarkable 1 fine with rmview, how did you install it?
