### ISSUE TITLE
not picking up rmview.json or RMVIEW_CONF

### ISSUE THREAD

**Issue by grobins** [bordaigorl/rmview#7]
I've tried with both of these and rmview.py still requires the IP and password.  I'm running with 
`python3 rmview.py rmview.json`

the contents of my rmview.json is

`{
  "ssh": {
    "address": "XXXXXXXX",
    "username": "root",
    "password": "XXXXXXXX"
    "timeout": 1
  },
  "orientation": "portrait",
  "pen_size": 10,
  "pen_color": "red",
  "fetch_frame_delay": 0.03
  "lz4_path_on_remarkable": "/usr/opt/lz4"
}`

But if I misspell rmview.json it doesn't through an error, so I'm guessing it's ignoring the argument.

**Comment by bordaigorl** [comment]
There's a missing comma before `"timeout"`, maybe that's it?
In the console you should see the configuration that is used.
Malformed JSON files are treated the same as missing files...

**Comment by grobins** [comment]
I can't believe I missed that! Sorry for the stupid question
