### ISSUE TITLE
Automatically connect on `rmview` command, rather than having to press enter twice?

### ISSUE THREAD

**Issue by jaanli** [bordaigorl/rmview#70]
`rmview` is incredible and has changed all my zoom meetings!!! Thank you!!!

Had a quick question that I couldn't find an answer to in the README: 

How can I switch the popup from coming up every time I run `rmview`? Right now I need to press enter twice, but it seems like it should be possible to have it automatically connect to the IP. 

This is the popup where I need to press enter twice:

![image](https://user-images.githubusercontent.com/5317244/116757705-986b4c00-a9dc-11eb-9508-33ddfb8d017f.png)

**Comment by stheid** [comment]
you can set the default addres in the config files (i think the readme explains how they work). Than it should work without that hastle

**Comment by jaanli** [comment]
Thanks for the pointer @stheid ! Although there was only one IP address in the "address" field of the json config, it was enclosed in square brackets (i.e. a list). Removing the square brackets removed the prompt :)
