### ISSUE TITLE
Still I can't make it work! Help please

### ISSUE THREAD

**Issue by paoloc971** [bordaigorl/rmview#72]
I get the error " libcrypto could not be decompressed on the tablet". Was it solved? I didn't find the solution. Please help me making it work!!! Thanks

**Comment by stheid** [comment]
I think you should have a look at #57.

**Comment by bordaigorl** [comment]
@paoloc971 I assume you are using the `update2.6` branch.
Could you please give the full error you get?
There should be a number in square brackets just after the "ibcrypto could not be decompressed on the tablet" message.
Knowing that could be helpful.

I just pushed adb3249d7727cc7ac5252575a14d28a442d468db a version where decompression is not necessary.
Could you check out that branch, pull, reinstall rmview and see if it works?

**Comment by elane001** [comment]
last update I downloaded the .zip and successfully installed the needed library but somehow this recent update, nothing is going correctly. 

when I run the code on the wiki, it can't find my file, I dunno what I'm doing wrong
when I run the code from #57  it tells me my RSA key is wrong. I looked at my RSA key but I don't know how to get the right key.
