### ISSUE TITLE
Incorrect instructions for Manually Closing VNC server

### ISSUE THREAD

**Issue by Mikowmer** [bordaigorl/rmview#73]
When stopping the rmview service when the reMarkable device is sleeping, rmview can't stop the VNC service on the device.
Good news: It tells you this, and gives you instructions on how to stop the service manually.
Bad news: It gives you incorrect instructions on how to stop the service manually.

What it says:
You can manually terminate it by running `ssh {IP address of device} killall rM-vnc-server-standalone`.

Why this is a problem:
Unless your username is root, this will not work, as the default username for ssh is your username.

What it should say:
You can manually terminate it by running `ssh root@{IP address of device} killall rM-vnc-server-standalone`.

Branch used is version2.6

**Comment by bordaigorl** [comment]
Ah thanks for the feedback!
I keep forgetting this issue because I configured the user in the ssh config 🤦🏻 
I'll fix it
