### ISSUE TITLE
I'm on 2.7 firmware, and rmview is not working.

### ISSUE THREAD

**Issue by cindy-jth** [bordaigorl/rmview#77]
![image](https://user-images.githubusercontent.com/65687259/119242113-72dbe900-bb29-11eb-9d97-e1d8cb9851f4.png)

**Comment by bordaigorl** [comment]
Have you looked at #57 ?

**Comment by cindy-jth** [comment]
I did install libcrypto.so.1.0.2 onto my rm2, but it's giving me this message.

**Comment by Maia421** [comment]
> I did install libcrypto.so.1.0.2 onto my rm2, but it's giving me this message.

Exact same problem here. Just copied the fix that was done for 2.6 and it doesn't seem to work on 2.7 :(

**Comment by elane001** [comment]
> I did install libcrypto.so.1.0.2 onto my rm2, but it's giving me this message.

same here. I did this to fix it for update 2.6 and it worked but now for 2.7 it doesn't seem to work

**Comment by ddund** [comment]
I'm going to counter the others and say that I'm also on 2.7 and followed [the instructions in the wiki](https://github.com/bordaigorl/rmview/wiki/Installing-missing-libcrypto-on-RM2-v2.6-or-above) and have no problem getting it to work.

**Comment by macoj** [comment]
I am on 2.7.0.51. Doing exactly what is on https://github.com/bordaigorl/rmview/wiki/Installing-missing-libcrypto-on-RM2-v2.6-or-above worked for me.

**Comment by bmaderbacher** [comment]
Apparently the old libcrypto file is deleted by a software update. I had to add it again after updating from 2.7.0.51 to 2.7.1.53, now it is working again.

**Comment by bordaigorl** [comment]
@bmaderbacher thanks for reporting, that might just be what the others were missing to realise!

**Comment by mitkovaelena** [comment]
Hi! I get the same error despite having downloaded the libcrypto.co.1.0.2.
I am on version 2.8.0.98. Any news?

**Comment by mitkovaelena** [comment]
Hey! For everyone looking at the WCP section in the wiki page https://github.com/bordaigorl/rmview/wiki/Installing-missing-libcrypto-on-RM2-v2.6-or-above
Keep in mind that you have to paste the library in usr/lib instead of usr/bin :))
@bordaigorl, I guess it's a typo?

**Comment by bordaigorl** [comment]
@mitkovaelena yes it's a typo! Thanks for pointing that out.
That's now corrected.
[btw the wiki is editable :)]
