### ISSUE TITLE
Suggestion: Add a fading trail

### ISSUE THREAD

**Issue by saludes** [bordaigorl/rmview#8]
I really like this project and I intend to use it in my remote teaching. 

There is something that I like in _Google Jamboard_ that I think will be a fine addition to this project: It is the ability to show a fading trail following the pen when you hover (but not press) over the screen. It is great for pointing/circling things while explaining. Ideally, a parameter in `config` would control for the length/duration of this trial.

**Comment by bordaigorl** [comment]
It's now a feature of both branches!
