### ISSUE TITLE
Not working w/ reMarkable OS 2.8.0.98 -- libcrypto.so.1.0.2 not found

### ISSUE THREAD

**Issue by larsblumberg** [bordaigorl/rmview#82]
Looks like due to missing `libcrypto.so.1.0.2`

> Please check your reMarkable is properly configured, see the documentation for instructions.
> Failed to start VNC server on reMarkable: /home/root/rM-vnc-server-standalone: error while loading shared libraries:
> libcrypto.so.1.0.2: cannot open shared object file: No such file or directory

**Comment by bordaigorl** [comment]
Have you tried with the workaround at https://github.com/bordaigorl/rmview/wiki/Installing-missing-libcrypto-on-RM2-v2.6-or-above ?
This is a known issue and the workaround should fix it.

**Comment by larsblumberg** [comment]
thanks, that fixed it.

@bordaigorl I'd like to go back to the master branch for the docker runner and avoid using the devel branch b/c I assume that the master branch is stable. Are you planning to merge back devel at some point?

**Comment by bordaigorl** [comment]
@larsblumberg yes the plan for releasing the devel branch is here #63 
I just need somebody with RM2 to test the new server (at the test-new-server branch) and if that works the last few items would be resolved.
