### ISSUE TITLE
 rM2 display frozen under v2.8.0 and with rm2fb

### ISSUE THREAD

**Issue by emvazquez** [bordaigorl/rmview#84]
Hello,

Launching rM2-vnc-server-standalone freezes the display of the rM2 under firmware version 2.8.0.

I have also rm2fb installed from Toltec / testing.

Where to start to diagnose the problem?

Best,
Emmanuel

**Comment by bordaigorl** [comment]
Have you seen the instructions in the [Readme](https://github.com/bordaigorl/rmview#warning-for-remarkable-2-users-warning)?

> ### :warning: For reMarkable 2 users :warning:
> rMview should work out of the box with the stock firmware version 2.5 or below.
>
> For 2.6 and above, for the moment you need to copy an extra library to the tablet. The process has not been automated yet. Please see [the wiki](https://github.com/bordaigorl/rmview/wiki/Installing-missing-libcrypto-on-RM2-v2.6-or-above) for instructions.
>
> If you use [`rm2fb`](https://github.com/ddvk/remarkable2-framebuffer) there are known compatibilities issues that are [being addressed](https://github.com/pl-semiotics/rM-vnc-server/issues/5).

For the moment you'd need to disable `rm2fb` if you want to use rmView.
The author of the server is aware of the issue but has not found the time to make a new release that is compatible with `rm2fb`.

**Comment by emvazquez** [comment]
ok thank you very much for taking the time to reply to my issue, and sorry. Indeed, removing rm2fb resolves the issue
