### ISSUE TITLE
rmview host window not updating properly (rM1 2.9.0.153)

### ISSUE THREAD

**Issue by rgayler** [bordaigorl/rmview#89]
I have just installed rmview for the first time, so maybe something is not configured correctly.

I have an **rM1** tablet running fw V 2.9.0.153
I have not installed any nonstandard software on the tablet other than rmview.
The tablet is connected to the host computer via USB
The host computer is a laptop running Ubuntu 21.04

rmview appears to launch correctly on the host:
**[image redacted]**
I assume the warning about the `service_identity` module is not really a problem because the VNC server connects.

The host rmview window correctly displays the state of the rM1 at the time of connection:
![image](https://user-images.githubusercontent.com/5409051/128495233-f0a931dd-081e-4ff5-bb38-decaf069d0ab.png)

When I draw on the tablet, the host window displays the pen actions, but the lines are not displayed.
(Actually, it leaves a faint trail of dots where the pen has been. If you look carefully at the image above you can just see some faint lines of dots.)

If I navigate the tablet to a different page of the document or a different document, the host window is not updated at all.

Do you have any suggestions how I could start to diagnose what is happening here?

Thanks

**Comment by bordaigorl** [comment]
Hi, as mentioned in #86  #87 support for 2.9 is currently not there, and will not be there until 2.9 is officially released (I myself haven't received it yet).
The 2.9 software has a built-in server; if you enable that and use the patched version of rmview [here](https://github.com/ddvk/rmview/tree/vnc29) it should work as expected.
Hopefully 2.9 will be released soon and that branch be merged in the official version.

P.S.: it's probably wise not to share output that embeds your password, hence I removed the screenshot of the log from your post.

**Comment by rgayler** [comment]
Thanks, @bordaigorl .

> support for 2.9 is currently not there, and will not be there until 2.9 is officially released 

2.9 got pushed to my reMarkable a couple of days ago, but I can see that I am enrolled in the beta program, so it must have been pushed as a beta.

> as mentioned in #86 #87

When I searched gitHub I thought #86 was specific to the rM2 and didn't pick up  that #87 was relevant because being an rmview noob I didn't realise it was a VNC related issue.

> the patched version of rmview here ... should work as expected

I confirm that does work, after following the LiveStream dialog on the rM1.

> wise not to share output that embeds your password

Thanks for that. I wasn't expecting a program to echo a password into the logging stream, so didn't check the output before i pasted it. Luckily my rM1 is always running behind a firewall, so the risk is probably small - but as you say, better not to share.

**Comment by bordaigorl** [comment]
> I wasn't expecting a program to echo a password into the logging stream

That's fair enough, the new version in the devel branch indeed takes care of that.
Glad the patched version works!

**Comment by rgayler** [comment]
I am closing this issue because it is fully resolved for me and it is just an instance of other issues that are dealing with it. I apologise in advance if that's bad etiquette (i don't know who is expected  to be responsible for closing issues).
