### ISSUE TITLE
Cant get rmview to work

### ISSUE THREAD

**Issue by ando600** [bordaigorl/rmview#90]
Hi, sorry for the seemingly stupid question, but I can seem to find a solution online. I have installed and configured rmview, but I cant get it to connect to my device. I can ssh into the device, and I can access the files over the web interface, but every time I try to use rmview, I get an error:

Could not connect to 10.11.99.1: No existing session
Please check your remarkable is connected and retry.
No existing session

Also, on ubuntu, I cant seem to get a reliable usb over Ethernet connection. Every time I connect the remarkable, I have to run dhcpcd on the usb adapter. I wonder if the two issues are related.

Thanks for your help!

**Comment by bordaigorl** [comment]
What version of remarkable firmware are you on?
Also: how did you install rmview? Did you auto-install the server?

**Comment by ando600** [comment]
I have the latest version, 2.9.0.210 installed. I tried the auto install, then did the manual install as well. The vnc server is on the remarkable, verified with ssh.

**Comment by bordaigorl** [comment]
Then see the pinned issue #86 and PR #87
