### ISSUE TITLE
VNC Server not working on 2.9.1.x (red marker, but no text)

### ISSUE THREAD

**Issue by seanelvidge** [bordaigorl/rmview#91]
Hi all,

I know a number of issues have already discussed problems with 2.9.x, I believe I have tried everything in each of them, and have a different issue remaining (hence creating the new post). Sorry if I've missed something!

I have rmview installed from ddvk:vnc29 on Ubuntu 20.04.01 and am running a rM2 with software 2.9.1.217.

Starting ScreenShare first and then opening rmview I can connect to the tablet and then get the white screen load. As I write on the rM I can see the red "marker" for where I am writing shows on my desktop, but no writing then actually appears on the desktop and just remains white.

Looking at the rmview output there is an error after it confirms the connection to the rM, specifically:

"peek: Input/output error".

Strongly appreciate any help anyone can provide, meant to be giving a seminar on Zoom tomorrow and can no longer connect (I had auto-updates turned on, which has now been "fixed" (turned off) to avoid this issue in the future!).

**Comment by RDeRenzi** [comment]
Sorry comment removed, does not work

**Comment by seanelvidge** [comment]
@RDeRenzi your comment made me go back to Step 1 and try everything again and I found my mistake! Everything is working now, here are the steps I did:

- download the VNC server from [here](https://goto.ucsd.edu/~lucy/ephemera/ef733978884a6301545b8c679c170019eb31c35b613b0e2b461d8fddcc962e6f/rm2/bin/rM2-vnc-server-standalone).
- Copy the file to the tablet with: `scp rM2-vnc-server-standalone root@REMARKABLE_IP:'$HOME/rM-vnc-server-standalone' `
- Make the file executable with `ssh root@REMARKABLE_IP chmod +x '$HOME/rM-vnc-server-standalone' `
- Restart tablet
- Download rmview from ddvk:  `git clone https://github.com/ddvk/rmview.git`
- **Make sure you change the branch!**:  `git checkout vnc29`
- Install rmview: `pip install .`
- Start ScreenShare on the rM notebook you want to share
- Run `rmview` and enter your IP address and password

Success!

**Comment by c-i-p-h-e-r** [comment]
It works but the response time suffers a lot when the page changes. One of the reasons I loved rmview was the sub-second latency. While this is still fine for the changes while we are in the same page/slide (I guess the damage tracking info updation works as before). However, when the page is changed in the reMarkable (I have rM1), it takes a lot of time to update on-screen. I miss the old rmview.

**Comment by bordaigorl** [comment]
@seanelvidge the new version of rmview now supports 2.9+ via ScreenShare.

@c-i-p-h-e-r I also prefer the server rmview was using until 2.7, but it takes work to make it work on 2.9, @pl-semiotics is on it but there's no timeline. Whenever there will be progress on that front, rmview will incorporate it.

**Comment by zelomel** [comment]
I just updated my rM1 to 2.9  (and applied ddvk hacks) and try to use rmview as before but it's not working.
Screen share is working using wifi, but rmview was working using usb this why I prefer rmview.

When I use rmview (binaries for win10), it connects, I can see my cursor/pen (red our blue dot), I can see my rM but the page doesn't refresh.
When I use rmview after starting screen share, it connects, I can see my cursor/pen (red our blue dot) but the page is blank.

What did I miss ?

Do you know if it is possible to use screenshare by USB ?

**Comment by bordaigorl** [comment]
@zelomel the binaries are for an old release of rmview which does not support 2.9.
For the moment you'd need to use the latest version installed with one of the methods in the readme.
I'll publish a new bundle at some point but I wanted to do that once support for 2.10 settled as well.

**Comment by zelomel** [comment]
OK it works.
Thank you for your reply.

**Comment by mkamensky** [comment]
Could someone summarise the situation at the moment? When I follow the instructions in the README, I end up with the same problem. This is with ver 2.10. Thanks!

**Comment by bordaigorl** [comment]
@mkamensky which instructions are you following? If you install through `pip` you should have no problem...

**Comment by mkamensky** [comment]
Yes, I installed with pip, I have precisely the problem described here: red marker, but no other changes

**Comment by mkamensky** [comment]
Except I do not have a line `peek: Input/output error.`

**Comment by bordaigorl** [comment]
@mkamensky ignore my comment on pip I got confused with a different issue.
Support for 2.10 only comes in the form of interoperability with the new ScreenShare function.
So you need to open a document, activate ScreenShare, then run rmview. After few seconds you should get the screen updates.

**Comment by mkamensky** [comment]
> @mkamensky ignore my comment on pip I got confused with a different issue. Support for 2.10 only comes in the form of interoperability with the new ScreenShare function. So you need to open a document, activate ScreenShare, then run rmview. After few seconds you should get the screen updates.

Yes, I did precisely that, but the screen does not update, beyond the red marker. Thanks...

**Comment by bordaigorl** [comment]
@mkamensky could you open a new issue? Your problem seems totally unrelated to this issue (symptom is similar but it's not a problem of the server as you are using ScreenShare and you are not on 2.9).
What would help in the new issue is to make sure you are running the latest version of rmview, to know the subversion of 2.10 you are on (are you on beta?), RM1 or RM2, and if you could run `rmview -v` so the output on the console would give us more clues.

**Comment by mkamensky** [comment]
> @mkamensky could you open a new issue?
Done, #107. Thanks!
