### ISSUE TITLE
Problem installing/upgrading rmview

### ISSUE THREAD

**Issue by antonmry** [bordaigorl/rmview#96]
I can install rmview as usual with `pip3 install .` but when I launch it:

```
$ rmview
Traceback (most recent call last):
  File "/usr/local/bin/rmview", line 5, in <module>
    from rmview.rmview import rmViewMain
  File "/usr/local/lib/python3.9/site-packages/rmview/rmview.py", line 6, in <module>
    from .screenstream.common import KEY_Left, KEY_Right, KEY_Escape
ModuleNotFoundError: No module named 'rmview.screenstream'
```

It happens with the `vnc` branch but it works with old ones.

**Comment by bordaigorl** [comment]
Thanks for reporting.
It should be fixed now, just pull and then run `pip install .` again.
I did not know you need to list all the subpackages in `setup.py` and `rmview.screenstream` is a new subpackage that was in the repo but not esplicitly mentioned in `setup.py`. It is now.

**Comment by antonmry** [comment]
it works now with the Screen Share option. Thanks!!
